services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./storage:/app/storage
    environment:
      - STORAGE_DIR=/app/storage
      - DATA_FILE=/app/storage/data.json
      - PORT=3000
